sequenceDiagram
  Service metrics->> Metrics generator: get metrics
  Service metrics->> Metron agent: forward metrics
  Metron agent->> Doppler: forward metrics
  Doppler->> Traffic controller: forward metrics
