sequenceDiagram
  Metrics generator->> Service metrics: metrics
  Service metrics->> Metron agent: forward metrics
  Metron agent->> Doppler: forward metrics
  Doppler->> Traffic controller: forward metrics
